# Minimal Server Configuration
host: 127.0.0.1
# host: 172.18.0.110
port: 15000
app_name: chasis
version: 1

# MongoDB Server Configuration
# Example URL: "mongodb+srv://<username>:<password>@<cluster-url>/< db_name>"
mongo:
  db_name: "tradingbotdb"
  uri: "mongodb://dGv07Ou:jVtwAwOfNH01SFjh@172.18.0.111:27017/?authSource=admin"
  # uri: "mongodb://localhost:27017/traderbotdb"


# Logger Utilitary Configuration
logger:
  enable: true
  logs_file_path: logs/traderbot.log


# Authentification Utilitary Configuration
auth:
  enabled: true
  token_time: 1000 # In seconds
  token_length: 30 # Number of characters


# Swagger Sistem Configuration
swagger:
  enabled: true # Disable only OpenApi3 validation, Docs is enabled
  title: Swagger Chasis
  version: 1.0.0
  path: /docs/
  layout: StandaloneLayout  # or BaseLayout
  deepLinking: true
  displayOperationId: true
  defaultModelsExpandDepth: 5
  defaultModelExpandDepth: 5
  defaultModelRendering: model
  displayRequestDuration: true
  docExpansion: list
  filter: true
  showExtensions: true
  showCommonExtensions: true
  supportedSubmitMethods: get
  test: "get,put,post,delete"
  validatorUrl: null
  withCredentials: true

